# Generated by Django 2.1.7 on 2019-03-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='feature_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
