# Generated by Django 2.1.7 on 2019-03-11 20:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='feature_image',
            field=models.ImageField(null=True, upload_to=app.models.article_feature_img_path),
        ),
    ]
